# Generated by Django 3.2.13 on 2022-05-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20220511_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='x',
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(help_text='05xxxxxxxx', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
