# Generated by Django 3.2.13 on 2022-05-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220511_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(default='05', help_text='05xxxxxxxx', max_length=10, null=True, unique=True),
        ),
    ]
