# Generated by Django 3.2.13 on 2022-05-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220512_1359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student_Model'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='Student_Table',
        ),
    ]
