# Generated by Django 3.2.13 on 2022-05-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gendar',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
