# Generated by Django 3.2.13 on 2022-05-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_student_gendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(error_messages={'uniqe': 'تم اضافة هذا الطالب سابقا ...'}, max_length=100, null=True, unique=True, verbose_name='Student Name'),
        ),
    ]
