# Generated by Django 4.0.4 on 2022-05-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_student_options_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='description',
        ),
        migrations.AddField(
            model_name='student',
            name='created',
            field=models.DateTimeField(null=1),
            preserve_default=1,
        ),
    ]
