# Generated by Django 3.2.13 on 2022-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='check your opinion',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(error_messages={'unique': 'تم اضافة هذا الطالب سابقا ...'}, max_length=100, null=True, unique=True, verbose_name='Student Name'),
        ),
    ]
