# Generated by Django 4.0.4 on 2022-05-14 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_student_options_remove_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=1),
        ),
    ]
