# Generated by Django 3.2.13 on 2022-05-11 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220511_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='check your opinion',
            new_name='Srvice Agreement',
        ),
        migrations.AddField(
            model_name='student',
            name='dem',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joined_date_time',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='joined_time',
            field=models.TimeField(null=True),
        ),
    ]
