# Generated by Django 4.0.4 on 2022-05-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_student_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created',
        ),
        migrations.AddField(
            model_name='student',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
