# Generated by Django 3.2.13 on 2022-05-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_file',
            field=models.FileField(null=True, upload_to='myapp/uploads'),
        ),
    ]
