# Generated by Django 3.2.13 on 2022-05-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_character_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='movies',
            field=models.ManyToManyField(to='myapp.Movie'),
        ),
    ]
